/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg05160000241_05160000163.proje2;


import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import java.util.NoSuchElementException;


public class Gui extends javax.swing.JFrame {
static DoublyLinkedList list = new DoublyLinkedList();
    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        JPAnaPanel = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        JTAYazdirmaAlani = new javax.swing.JTextArea();
        JTAdiSoyadi = new javax.swing.JTextField();
        JTNumaralari = new javax.swing.JTextField();
        JLAdıSoyadı = new javax.swing.JLabel();
        JLNumaraları = new javax.swing.JLabel();
        JBKisiEkle = new javax.swing.JButton();
        JBKisiSil = new javax.swing.JButton();
        JBYazdir = new javax.swing.JButton();
        JBTerstenYazdir = new javax.swing.JButton();
        JBCikis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTAYazdirmaAlani.setColumns(20);
        JTAYazdirmaAlani.setLineWrap(true);
        JTAYazdirmaAlani.setRows(50);
        jScrollPane.setViewportView(JTAYazdirmaAlani);

        JTNumaralari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTNumaralariActionPerformed(evt);
            }
        });

        JLAdıSoyadı.setText("Adı ve Soyadı");

        JLNumaraları.setText("Numaraları (Virgül ile ayırınız)");

        JBKisiEkle.setText("Kişi Ekle");
        JBKisiEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBKisiEkleActionPerformed(evt);
            }
        });

        JBKisiSil.setText("Kişi Sil");
        JBKisiSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBKisiSilActionPerformed(evt);
            }
        });

        JBYazdir.setText("Kişileri Yazdır (A-Z)");
        JBYazdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBYazdirActionPerformed(evt);
            }
        });

        JBTerstenYazdir.setText("Kişileri Yazdır(Z-A)");
        JBTerstenYazdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTerstenYazdirActionPerformed(evt);
            }
        });

        JBCikis.setText("Kaydet ve Çık");
        JBCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCikisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPAnaPanelLayout = new javax.swing.GroupLayout(JPAnaPanel);
        JPAnaPanel.setLayout(JPAnaPanelLayout);
        JPAnaPanelLayout.setHorizontalGroup(
            JPAnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPAnaPanelLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(JBYazdir, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBTerstenYazdir, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPAnaPanelLayout.createSequentialGroup()
                .addGroup(JPAnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPAnaPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane))
                    .addGroup(JPAnaPanelLayout.createSequentialGroup()
                        .addGroup(JPAnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JLAdıSoyadı, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLNumaraları, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(JPAnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTAdiSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JPAnaPanelLayout.createSequentialGroup()
                                .addComponent(JTNumaralari, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JBKisiEkle)
                                .addGap(18, 18, 18)
                                .addComponent(JBKisiSil)))))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPAnaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBCikis)
                .addGap(53, 53, 53))
        );
        JPAnaPanelLayout.setVerticalGroup(
            JPAnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPAnaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPAnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JTAdiSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPAnaPanelLayout.createSequentialGroup()
                        .addComponent(JLAdıSoyadı, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addGroup(JPAnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JPAnaPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(JPAnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTNumaralari, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBKisiEkle)
                            .addComponent(JBKisiSil)))
                    .addGroup(JPAnaPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(JLNumaraları, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(JPAnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBYazdir)
                    .addComponent(JBTerstenYazdir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(JBCikis)
                .addContainerGap())
        );

        getContentPane().add(JPAnaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 500));

        pack();
    }// </editor-fold>                        

    private void JTNumaralariActionPerformed(java.awt.event.ActionEvent evt) {                                             
        
    }                                            

    private void JBKisiEkleActionPerformed(java.awt.event.ActionEvent evt) {                                           
        try{
        String AdSoyad = JTAdiSoyadi.getText();
        String Numaralari = JTNumaralari.getText();
        String Line = AdSoyad+","+Numaralari;
        Bilgi kisi = new Bilgi(Line);
        
        list.siraliEkle(kisi);
        JOptionPane.showMessageDialog(JPAnaPanel, "Kayıt Başarıyla Eklendi.");
        }
        catch (NoSuchElementException e){
           JOptionPane.showMessageDialog(JPAnaPanel, "Girilen bilgiler eksik "
                   + "veya hatalı lütfen kontrol ediniz");
        }
        
    }                                          

    private void JBKisiSilActionPerformed(java.awt.event.ActionEvent evt) {                                          
      if(list.kisiyiSil(JTAdiSoyadi.getText())){
      JOptionPane.showMessageDialog(JPAnaPanel,"Kayıt başarıyla silindi");
    }
      else{
      JOptionPane.showMessageDialog(JPAnaPanel,"Girdiğiniz isim rehberde bulunamadı");
      }
    }                                         

    private void JBYazdirActionPerformed(java.awt.event.ActionEvent evt) {                                         
        JTAYazdirmaAlani.append(list.listeyiYazdir());
    }                                        

    private void JBTerstenYazdirActionPerformed(java.awt.event.ActionEvent evt) {                                                
       JTAYazdirmaAlani.append(list.terstenYazdir());
    }                                               

    private void JBCikisActionPerformed(java.awt.event.ActionEvent evt) {                                        
           DoublyLinkedList.dosyayaYazdir();
              System.exit(0);     
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        Scanner fileIn = null;
        try {
            fileIn = new Scanner(new FileInputStream("Rehber.txt"));
        }
        catch (FileNotFoundException e) {
            System.out.println("File Not Found!");
            System.exit(0);
        }
     
    while(fileIn.hasNextLine()){
    String Line = fileIn.nextLine();
    Bilgi kisi = new Bilgi(Line);
        
    list.siraliEkle(kisi);
              
    }
    fileIn.close();
    
        

    
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton JBCikis;
    private javax.swing.JButton JBKisiEkle;
    private javax.swing.JButton JBKisiSil;
    private javax.swing.JButton JBTerstenYazdir;
    private javax.swing.JButton JBYazdir;
    private javax.swing.JLabel JLAdıSoyadı;
    private javax.swing.JLabel JLNumaraları;
    private javax.swing.JPanel JPAnaPanel;
    private javax.swing.JTextArea JTAYazdirmaAlani;
    private javax.swing.JTextField JTAdiSoyadi;
    private javax.swing.JTextField JTNumaralari;
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration                   
}
